__all__ = [
	"NativePeerAddress",
	"NativePeerMethod",
	"PeerData"
]


from typing import TypedDict


class NativePeerAddress(TypedDict):
	address: str
	port: int


class NativePeerMethod(TypedDict):
	def getRTT() -> int: ...
	def getState() -> int: ...
	def getChannelCount() -> int: ...
	def getConnectID() -> int: ...
	def getIncomingBandwidth() -> None: ...
	def getOutgoingBandwidth() -> None: ...
	def getPacketsLost() -> int: ...
	def getPacketsSent() -> int: ...
	def getTotalWaitingData() -> int: ...
	def getAddress() -> NativePeerAddress: ...


class PeerData(TypedDict):
	netID: int
	enet: NativePeerMethod